name: Auto deploy using gh-pages package

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. checkout repo
      - name: Checkout source code
        uses: actions/checkout@v5

      # 2. Setup node
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 22.15.0
          cache: npm
      
      # 3. Install dependencies (uses cache if unchanged)
      - name: Install dependencies
        run: npm ci

      # 4. Configure git user
      - name: Configure git user
        run: |
          git config --global user.name "omsai-git"
          git config --global user.email "omsai.kusuma@gmail.com"

      # 5. Build and deploy react app using gh-pages package
      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run deploy

      